# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.13'
    windows:
      imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)

trigger:
- master

steps:
- checkout: self 
  submodules: true
- task: CMake@1
  inputs:
    cmakeArgs: .. -DBUILD_TOOLS=ON
- script: cmake --build .
  workingDirectory: build
  failOnStderr: true
  displayName: 'Compile'